### ISSUE TITLE
Import synthetic data from view

### ISSUE THREAD

**Issue by duartelautaro5** [galizia-lab/pyview#41]
Hello everyone,

First, I would like to thank you for this amazing tool. I’ve been using PyView for years in the lab and it has been extremely helpful.

Now I am having issues when importing data into ILTIS. I even tried with the synthetic dataset to discard any problem with my own data. When I try to import, I get the following error:

AttributeError: Module 'scipy' has no attribute 'array'

I also tried installing an older version of SciPy with:
pip install "scipy==0.19.0"
but it didn’t work with my current setup (Python 3.10).

Has anyone else encountered this problem? Do you know how to fix it or if there is a workaround?

Thanks a lot in advance!

**Comment by galizia** [comment]
Dear duartelautaro5,

thanks for using pyView! 
Keeping pyView in line with all the new requirements of the many packages in the system is a nightmare - and scipy is only a minor of our problems.

On one hand, we want to keep the ‘master’ as we’ve published it, on the other hand we need to keep it up to date with all new developments. 

If you are in immediate need for a solution, try to download the branch “gio_jan23” instead of “master”. That is the branch we are currently using and it works well with us, but we did not test it thoroughly on different machines yet. 
Please let me know if that works for you!

Best,
Giovanni

*******************
Prof. Dr. Giovanni Galizia
Director of the Zukunftskolleg, University of Konstanz
Professor Neurobiology and Zoology, University of Konstanz
Permanent Fellow Wissenschaftskolleg zu Berlin
 
***@***.***
http://neuro.uni.kn
*****************************

**Comment by duartelautaro5** [comment]
Dear Giovanni
Thank a lot for your response.

The problem came from using scipy for basic array operations, but recent versions of scipy no longer expose those functions. The solution I found was to switch everything to numpy for array manipulations in the Options_Object.py script. It has worked well so far!

If I encounter a new problem in the future, I will download the branch “gio_jan23” as you recommended.

Thanks again,
Lautaro

**Comment by galizia** [comment]
Dear Lautaro,

thanks for noting that numpy thing - we have now updated the program in the repository. Next time you download it, let us know if everything works fine! “gio_jan23” is not a valid branch any more, we have updated the master (and are working on ‘dev’ for future changes). 

Best,
Giovanni



*******************
Prof. Dr. Giovanni Galizia
Director of the Zukunftskolleg, University of Konstanz
Professor Neurobiology and Zoology, University of Konstanz
Permanent Fellow Wissenschaftskolleg zu Berlin
 
***@***.***
http://neuro.uni.kn
*****************************

**Comment by duartelautaro5** [comment]
Dear Giovanni,

I wanted to ask what you’re currently using to perform the shift correction in your calcium imaging data. I know that PyView doesn’t yet include this feature, so I was curious to know what tool or method you’re using at the moment.

Thank you very much in advance for your help.

**Comment by galizia** [comment]
Dear Lautaro,

sorry for the long delay in my response - I have been traveling and am now catching up with my mails. 

Yes, shift correction and automatic glomerulus segmentations are the sore points that are still missing. It is so annoying!

For movement corrections within one measurement, you could load the data in ImageJ - there are good plugins for movement correction there.
For shift corrections between measurements, that is more difficult. The key thing is that we would probably want to load all (good) measurements in one bee, and then export them as a single xyt matrix that can be loaded in ImageJ - and from there run the movement correction for the full animal. 

This latter option is something I have high on my priority list: load several measurements, and export them en block - also because glomerulus segmentation will work best on exactly this large xyt matrix. 
And, once we have a single xyt matrix, we should be able to implement movement correction tools from outside - there are several out there. 

So, bottom line: the tools to export the data individually as .tif files with the necessary information are implemented in pyView (I am quite sure, I would have to look up how exactly this is done), and with that, treating them with another program or with ImageJ should work. 

All very fuzzy still - but maybe you have the capacity to develop this further, and then we’ll implement your changes into the package for everybody to benefit!

Best,
Giovanni



*******************
Prof. Dr. Giovanni Galizia
Director of the Zukunftskolleg, University of Konstanz
Professor Neurobiology and Zoology, University of Konstanz
Permanent Fellow Wissenschaftskolleg zu Berlin
 
***@***.***
http://neuro.uni.kn
*****************************
